# Generated by Django 3.2.4 on 2021-08-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memberRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fstname', models.CharField(max_length=50)),
                ('user_lastmame', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=128)),
                ('user_pwd', models.CharField(max_length=50)),
            ],
        ),
    ]
