# Generated by Django 3.2.5 on 2021-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('seq', models.AutoField(db_column='SEQ', primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='TIME')),
                ('maxtemp', models.FloatField(blank=True, db_column='MAXTEMP', null=True)),
                ('mintemp', models.FloatField(blank=True, db_column='MINTEMP', null=True)),
                ('avgtemp', models.FloatField(blank=True, db_column='AVGTEMP', null=True)),
                ('day', models.DateField(blank=True, db_column='DAY', null=True)),
                ('hour', models.TimeField(blank=True, db_column='HOUR', null=True)),
            ],
            options={
                'db_table': 'Temp_Data',
                'managed': False,
            },
        ),
    ]
